-- 기존 큰 컬럼들을 TEXT로 변경 (필요시)
ALTER TABLE restaurants 
MODIFY COLUMN holiday_info TEXT,
MODIFY COLUMN opening_hours TEXT,
MODIFY COLUMN main_menu TEXT,
MODIFY COLUMN hashtags TEXT,
MODIFY COLUMN area_info TEXT;

-- 이미 존재하는지 확인 후 없는 컬럼만 추가
ALTER TABLE restaurants 
ADD COLUMN IF NOT EXISTS description TEXT NULL,
ADD COLUMN IF NOT EXISTS parking_info TEXT NULL,
ADD COLUMN IF NOT EXISTS transportation TEXT NULL,
ADD COLUMN IF NOT EXISTS special_notes TEXT NULL,
ADD COLUMN IF NOT EXISTS card_payment VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS cash_payment VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS mobile_payment VARCHAR(10) NULL,
ADD COLUMN IF NOT EXISTS account_transfer VARCHAR(10) NULL;

